#!/usr/bin/env node
/**
 * verify-site.mjs — dependency-free site validator.
 *
 *   node scripts/verify-site.mjs [--root <dir>] [--browser] [--update-baseline]
 *
 * Static checks (always): existing-page integrity, Articles output, SEO
 * metadata, JSON-LD vs CSP hashes, FAQ markup vs visible FAQ, sitemap,
 * robots, internal links.
 * --browser: also renders pages with Playwright if it is installed (JS off and
 * JS on, 360px wide) through a tiny local server that sends the netlify.toml
 * headers, so CSP violations are real. Reports page weight and request count.
 * --update-baseline: deliberately re-record the existing-page baseline.
 * Exit code 1 if any check fails.
 */
import { readFileSync, readdirSync, existsSync, statSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import { createServer } from "node:http";
import { createRequire } from "node:module";
import { execSync } from "node:child_process";
import { dirname, join, resolve, extname } from "node:path";
import { fileURLToPath } from "node:url";

const args = process.argv.slice(2);
const ri = args.indexOf("--root");
const ROOT = resolve(ri > -1 ? args[ri + 1] : join(dirname(fileURLToPath(import.meta.url)), ".."));
const SITE = "https://www.bizora-cm.com";
const MARKER = "generated by scripts/build-articles.mjs";
const EXISTING = ["index.html", "pages/features.html", "pages/pricing.html", "pages/support.html", "pages/faq.html", "pages/about.html", "404.html"];
const GENERIC = /^(click here|here|read more|more|link)$/i;
const BASELINE = join(ROOT, "scripts/existing-pages.baseline.json");

const read = (p) => readFileSync(join(ROOT, p), "utf8");
const sha = (s) => createHash("sha256").update(s).digest("base64");
let failures = 0, warnings = 0;
const section = (t) => console.log(`\n== ${t}`);
const ok = (m) => console.log(`  PASS ${m}`);
const bad = (m) => { failures++; console.log(`  FAIL ${m}`); };
const warn = (m) => { warnings++; console.log(`  WARN ${m}`); };
const check = (cond, pass, fail) => (cond ? ok(pass) : bad(fail));

function walk(d) {
  if (!existsSync(d)) return [];
  return readdirSync(d).flatMap((n) => { const p = join(d, n); return statSync(p).isDirectory() ? walk(p) : [p]; });
}
const rel = (p) => p.slice(ROOT.length + 1);
const canonicalOf = (html) => [...html.matchAll(/<link rel="canonical" href="([^"]*)"/g)].map((m) => m[1]);
const cspOf = () => read("netlify.toml").match(/Content-Security-Policy = "([^"]+)"/)[1];
const stripHashes = (csp) => csp.replace(/ 'sha256-[^']+'/g, "");
const ldBlocks = (html) => [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].map((m) => m[1]);

/* ---------------------------------------------------------------- baseline */
if (args.includes("--update-baseline")) {
  const sm = read("sitemap.xml");
  const original = sm.slice(0, sm.indexOf("</url>", sm.lastIndexOf("/pages/about.html")) + 6);
  const b = { pages: {}, sitemapOriginalSha: sha(original), cspWithoutHashes: stripHashes(cspOf()) };
  for (const p of EXISTING) { const h = read(p); b.pages[p] = { sha: sha(h), canonical: canonicalOf(h)[0] || null }; }
  writeFileSync(BASELINE, JSON.stringify(b, null, 2) + "\n");
  console.log("Baseline updated.");
  process.exit(0);
}
const baseline = JSON.parse(readFileSync(BASELINE, "utf8"));

/* ----------------------------------------------------------- existing pages */
section("Existing pages (must be untouched)");
for (const p of EXISTING) {
  if (!existsSync(join(ROOT, p))) { bad(`${p} is missing`); continue; }
  const h = read(p);
  check(sha(h) === baseline.pages[p].sha, `${p} byte-identical to baseline`, `${p} CHANGED since baseline`);
  check((canonicalOf(h)[0] || null) === baseline.pages[p].canonical, `${p} canonical unchanged`, `${p} canonical changed`);
}
const sitemap = read("sitemap.xml");
{
  const end = sitemap.indexOf("</url>", sitemap.lastIndexOf("/pages/about.html")) + 6;
  check(sha(sitemap.slice(0, end)) === baseline.sitemapOriginalSha, "sitemap.xml: original six entries unchanged", "sitemap.xml: original entries changed");
}

/* ------------------------------------------------------------ content model */
const cats = JSON.parse(read("content/categories.json"));
const arts = readdirSync(join(ROOT, "content/articles")).filter((f) => f.endsWith(".json") && !f.startsWith("_")).map((f) => JSON.parse(read(`content/articles/${f}`)));
const published = arts.filter((a) => a.status === "published");
const drafts = arts.filter((a) => a.status !== "published");
const usedCats = new Set(published.map((a) => a.category));

/* ----------------------------------------------------------------- articles */
section("Articles output");
const articleFiles = walk(join(ROOT, "articles")).filter((f) => f.endsWith("index.html")).map(rel);
check(articleFiles.includes("articles/index.html"), "articles/index.html exists", "articles/index.html missing");
for (const d of drafts) check(!articleFiles.includes(`articles/${d.slug}/index.html`), `no page for draft ${d.slug}`, `DRAFT page exists: ${d.slug}`);
const expected = new Set(["articles/index.html", ...published.map((a) => `articles/${a.slug}/index.html`), ...cats.filter((c) => usedCats.has(c.slug)).map((c) => `articles/category/${c.slug}/index.html`)]);
for (const f of articleFiles) check(expected.has(f), `${f} is expected`, `${f} is NOT expected (draft, empty category or stale)`);
for (const f of expected) check(articleFiles.includes(f), `${f} generated`, `${f} missing`);
for (const f of walk(join(ROOT, "articles"))) if (!f.endsWith("index.html")) bad(`stray file in articles/: ${rel(f)}`);
const emptyCatDirs = cats.filter((c) => !usedCats.has(c.slug) && existsSync(join(ROOT, `articles/category/${c.slug}`)));
check(emptyCatDirs.length === 0, "no empty category pages", `empty category pages: ${emptyCatDirs.map((c) => c.slug)}`);

/* -------------------------------------------------------------------- SEO */
section("SEO metadata & JSON-LD");
// Pages added after the baseline (not byte-locked, but fully checked below).
const ADDED = ["pages/demo.html", "pages/point-of-sale.html", "fr/index.html", "fr/point-de-vente/index.html"];
const allPages = [...EXISTING, ...ADDED, ...articleFiles];
const urlFor = (f) => f === "index.html" ? `${SITE}/` : (f.startsWith("articles/") || f.startsWith("fr/")) ? `${SITE}/${f.replace(/index\.html$/, "")}` : `${SITE}/${f}`;
const titles = new Map(), canons = new Map();
for (const f of allPages) {
  const h = read(f);
  const cs = canonicalOf(h);
  if (f === "404.html") continue;
  check(cs.length === 1, `${f}: exactly one canonical`, `${f}: ${cs.length} canonicals`);
  if (f.startsWith("articles/") || ADDED.includes(f)) check(cs[0] === urlFor(f), `${f}: canonical is ${urlFor(f)}`, `${f}: canonical ${cs[0]} != ${urlFor(f)}`);
  if (cs[0] && canons.has(cs[0])) bad(`duplicate canonical ${cs[0]} (${canons.get(cs[0])}, ${f})`); else canons.set(cs[0], f);
  const t = (h.match(/<title>([\s\S]*?)<\/title>/) || [])[1];
  if (titles.has(t)) bad(`duplicate <title> "${t}" (${titles.get(t)}, ${f})`); else titles.set(t, f);
}
for (const f of articleFiles) {
  const h = read(f);
  const must = ["<title>", 'name="description" content="', 'property="og:title"', 'property="og:description"', 'property="og:image"', 'property="og:url"', 'name="twitter:card"', 'name="twitter:title"', 'name="twitter:description"', 'name="twitter:image"', 'rel="canonical"', '<html lang="en">'];
  const missing = must.filter((m) => !h.includes(m));
  check(missing.length === 0, `${f}: title/description/OG/Twitter/lang present`, `${f}: missing ${missing}`);
  check((h.match(/<h1[\s>]/g) || []).length === 1, `${f}: exactly one H1`, `${f}: H1 count != 1`);
  check(!/hreflang/i.test(h), `${f}: no hreflang`, `${f}: unexpected hreflang`);
  const blocks = ldBlocks(h);
  check(blocks.length === 1, `${f}: one JSON-LD block`, `${f}: ${blocks.length} JSON-LD blocks`);
  let graph = [];
  try { graph = JSON.parse(blocks[0])["@graph"] || []; } catch (e) { bad(`${f}: JSON-LD does not parse (${e.message})`); }
  const types = graph.map((n) => n["@type"]);
  const isArticle = /^articles\/[^/]+\/index\.html$/.test(f);
  if (isArticle) {
    check(types.includes("Article") && types.includes("BreadcrumbList"), `${f}: Article + BreadcrumbList JSON-LD`, `${f}: missing Article/BreadcrumbList`);
    const a = published.find((x) => `articles/${x.slug}/index.html` === f);
    const visibleFaq = (h.match(/<section class="article-faq"/g) || []).length > 0;
    const ldFaq = graph.find((n) => n["@type"] === "FAQPage");
    check(visibleFaq === !!ldFaq, `${f}: FAQPage JSON-LD only with visible FAQ`, `${f}: FAQ markup (${!!ldFaq}) != visible FAQ (${visibleFaq})`);
    if (ldFaq) {
      const vis = [...h.matchAll(/<h3>([\s\S]*?)<\/h3>\s*<p>([\s\S]*?)<\/p>/g)].map((m) => [m[1], m[2]]);
      const un = (s) => s.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"');
      const same = ldFaq.mainEntity.length === a.faq.length && ldFaq.mainEntity.every((q, i) => vis.some(([vq, va]) => un(vq) === q.name && un(va) === q.acceptedAnswer.text));
      check(same, `${f}: FAQ JSON-LD matches visible FAQ text`, `${f}: FAQ JSON-LD differs from visible FAQ`);
    }
    const img = h.match(/<img class="article__image"[^>]*>/);
    if (img) check(/ width="\d+"/.test(img[0]) && / height="\d+"/.test(img[0]) && !/loading="lazy"/.test(img[0]) && /fetchpriority="high"/.test(img[0]) && /alt="[^"]+"/.test(img[0]), `${f}: featured image has width/height, alt, priority and is not lazy`, `${f}: featured image attributes wrong: ${img[0]}`);
    check(/<div class="article__body">\s*\S/.test(h), `${f}: article body present in static HTML`, `${f}: empty article body`);
    check(!/class="[^"]*\b(section|feature-card|reveal-init)\b/.test(h), `${f}: no scroll-reveal classes`, `${f}: uses scroll-reveal class`);
    check(!/src="[^"]*animations\.js"/.test(h), `${f}: animations.js not loaded`, `${f}: loads animations.js`);
  } else if (f.includes("/category/")) {
    check(types.includes("CollectionPage") && types.includes("BreadcrumbList"), `${f}: CollectionPage + BreadcrumbList`, `${f}: missing CollectionPage/BreadcrumbList`);
  } else check(types.includes("CollectionPage"), `${f}: CollectionPage JSON-LD`, `${f}: missing CollectionPage`);
}
{
  const idx = read("articles/index.html");
  const noindex = /name="robots" content="noindex/.test(idx);
  check(noindex === (published.length === 0), `articles/index.html robots (${noindex ? "noindex while empty" : "indexable, has content"})`, `articles/index.html robots mismatch (noindex=${noindex}, published=${published.length})`);
}

/* --------------------------------------------------------------- CSP hashes */
section("CSP / JSON-LD hashes");
const csp = cspOf();
const allowed = new Set([...csp.matchAll(/'sha256-([^']+)'/g)].map((m) => m[1]));
let ldCount = 0;
for (const f of allPages) for (const b of ldBlocks(read(f))) {
  ldCount++;
  check(allowed.has(sha(b)), `${f}: JSON-LD hash allowed by CSP`, `${f}: JSON-LD hash sha256-${sha(b)} NOT in CSP (structured data would be blocked)`);
}
console.log(`  (${ldCount} JSON-LD blocks checked across ${allPages.length} pages)`);
check(!/script-src[^;]*'unsafe-inline'/.test(csp), "script-src has no 'unsafe-inline'", "script-src contains 'unsafe-inline'");
check(!/script-src[^;]*'unsafe-eval'/.test(csp), "script-src has no 'unsafe-eval'", "script-src contains 'unsafe-eval'");
check(stripHashes(csp) === baseline.cspWithoutHashes, "CSP directives unchanged (only hashes differ)", "a CSP directive other than hashes changed");
const ownedBlock = (read("netlify.toml").match(/# ARTICLES-JSONLD-HASHES[\s\S]*?# END ARTICLES-JSONLD-HASHES/) || [""])[0];
const owned = [...ownedBlock.matchAll(/#\s+sha256-(\S+)/g)].map((m) => m[1]);
const neededByArticles = new Set(articleFiles.flatMap((f) => ldBlocks(read(f)).map(sha)));
check(owned.every((h) => neededByArticles.has(h)) && [...neededByArticles].every((h) => allowed.has(h)), "generator-owned hashes are exactly the ones in use", "stale or missing generator-owned hashes (re-run build-articles)");

/* ----------------------------------------------------------------- sitemap */
section("Sitemap & robots");
const locs = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
check((sitemap.match(/<url>/g) || []).length === (sitemap.match(/<\/url>/g) || []).length && sitemap.trim().startsWith("<?xml") && sitemap.trim().endsWith("</urlset>"), "sitemap.xml is well-formed", "sitemap.xml malformed");
check(new Set(locs).size === locs.length, "no duplicate sitemap URLs", "duplicate sitemap URLs");
const expectedLocs = new Set([...(published.length ? [`${SITE}/articles/`] : []), ...published.map((a) => `${SITE}/articles/${a.slug}/`), ...cats.filter((c) => usedCats.has(c.slug)).map((c) => `${SITE}/articles/category/${c.slug}/`)]);
const articleLocs = locs.filter((l) => l.startsWith(`${SITE}/articles`));
check(articleLocs.length === expectedLocs.size && articleLocs.every((l) => expectedLocs.has(l)), `sitemap article URLs = published content only (${articleLocs.length})`, `sitemap article URLs ${JSON.stringify(articleLocs)} != expected ${JSON.stringify([...expectedLocs])}`);
for (const l of articleLocs) check(l.endsWith("/"), `sitemap URL has trailing slash: ${l}`, `sitemap URL missing trailing slash: ${l}`);
for (const d of drafts) check(!locs.some((l) => l.includes(d.slug)), `draft ${d.slug} not in sitemap`, `DRAFT in sitemap: ${d.slug}`);
for (const f of ADDED) check(locs.includes(urlFor(f)), `${f} is in the sitemap`, `${f} is missing from the sitemap`);

/* ---- French pages: hreflang pairs must be reciprocal and point at real pages ---- */
section("French pages / hreflang");
const PAIRS = [["index.html", "fr/index.html"], ["pages/point-of-sale.html", "fr/point-de-vente/index.html"]];
const hreflangs = (h) => Object.fromEntries([...h.matchAll(/<link rel="alternate" hreflang="([^"]+)" href="([^"]+)"/g)].map((m) => [m[1], m[2]]));
for (const [en, fr] of PAIRS) {
  const he = read(en), hf = read(fr);
  const le = hreflangs(he), lf = hreflangs(hf);
  check(/<html lang="fr">/.test(hf), `${fr}: <html lang="fr">`, `${fr}: missing lang="fr"`);
  check(le.en === urlFor(en) && le.fr === urlFor(fr) && le["x-default"] === urlFor(en), `${en}: hreflang en/fr/x-default`, `${en}: hreflang set is wrong ${JSON.stringify(le)}`);
  check(lf.en === urlFor(en) && lf.fr === urlFor(fr) && lf["x-default"] === urlFor(en), `${fr}: hreflang en/fr/x-default (reciprocal)`, `${fr}: hreflang set is wrong ${JSON.stringify(lf)}`);
  check(!/data-config-text="nav\.primaryCtaLabel"/.test(hf), `${fr}: no English config text in French page`, `${fr}: uses English nav.primaryCtaLabel`);
  check(/main\.js\?v=/.test(hf), `${fr}: main.js is version-stamped (bypasses the 24h cache)`, `${fr}: main.js not version-stamped`);
}
const robots = read("robots.txt");
const disallows = [...robots.matchAll(/^Disallow:\s*(\S*)/gim)].map((m) => m[1]).filter(Boolean);
check(!disallows.some((d) => "/articles/".startsWith(d) || d.startsWith("/articles")), "robots.txt does not block /articles/", `robots.txt blocks: ${disallows}`);
check(/Sitemap:\s*https:\/\/www\.bizora-cm\.com\/sitemap\.xml/.test(robots), "robots.txt references the sitemap", "robots.txt sitemap line missing");

/* -------------------------------------------------------------------- links */
section("Internal links");
const resolveLocal = (href) => {
  const u = href.split("#")[0].split("?")[0];
  if (u === "/") return "index.html";
  const p = u.replace(/^\//, "");
  if (u.endsWith("/")) return `${p}index.html`;
  return p;
};
const pagesToScan = [...allPages, "components/navbar.html", "components/footer.html"];
let linkCount = 0;
for (const f of pagesToScan) {
  const h = read(f);
  const isArticlesPage = f.startsWith("articles/");
  for (const m of h.matchAll(/<a\b([^>]*)href="([^"]*)"([^>]*)>([\s\S]*?)<\/a>/g)) {
    const href = m[2];
    if (!href.startsWith("/") || href.startsWith("//")) continue;
    linkCount++;
    const target = resolveLocal(href);
    const exists = existsSync(join(ROOT, target));
    if (!exists) { (isArticlesPage || href.startsWith("/articles") ? bad : warn)(`${f}: broken internal link ${href}`); continue; }
    if (href.startsWith("/articles")) {
      check(href.endsWith("/"), `${f}: ${href} uses trailing slash`, `${f}: ${href} lacks trailing slash`);
      if (!expected.has(target)) bad(`${f}: links to non-published articles URL ${href}`);
    }
    const text = m[4].replace(/<[^>]+>/g, "").trim();
    const labelled = /aria-label="[^"]{8,}"/.test(m[1] + m[3]);
    if (isArticlesPage && !labelled && (GENERIC.test(text) || text === "")) bad(`${f}: non-descriptive link text "${text}" -> ${href}`);
  }
}
console.log(`  (${linkCount} internal links checked)`);
if (!failures) ok("no broken or invalid internal links, descriptive anchor text on Articles pages");

/* ---------------------------------------------------------------- rendering */
async function browserChecks() {
  section("Rendering, CSP and weight (Playwright)");
  const require = createRequire(import.meta.url);
  let pw;
  for (const c of [() => require("playwright"), () => require(join(execSync("npm root -g").toString().trim(), "playwright"))]) { try { pw = c(); break; } catch {} }
  if (!pw) { warn("Playwright not found; browser checks skipped"); return; }
  const toml = read("netlify.toml");
  const hdrBlock = toml.split('for = "/*"')[1].split("[[headers]]")[0];
  const headers = Object.fromEntries([...hdrBlock.matchAll(/^\s+([A-Za-z-]+) = "([^"]+)"/gm)].map((m) => [m[1], m[2]]));
  const MIME = { ".html": "text/html; charset=utf-8", ".css": "text/css", ".js": "text/javascript", ".png": "image/png", ".webp": "image/webp", ".jpg": "image/jpeg", ".ico": "image/x-icon", ".json": "application/json", ".xml": "application/xml", ".txt": "text/plain" };
  const server = createServer((req, res) => {
    const url = decodeURIComponent(req.url.split("?")[0]);
    let p = join(ROOT, url);
    if (url.endsWith("/")) p = join(p, "index.html");
    if (!p.startsWith(ROOT) || !existsSync(p) || statSync(p).isDirectory()) { res.writeHead(404, headers); return res.end("not found"); }
    res.writeHead(200, { ...headers, "Content-Type": MIME[extname(p)] || "application/octet-stream" });
    res.end(readFileSync(p));
  }).listen(0);
  await new Promise((r) => server.once("listening", r));
  const base = `http://127.0.0.1:${server.address().port}`;
  const exe = existsSync("/opt/pw-browsers/chromium") ? "/opt/pw-browsers/chromium" : undefined;
  const browser = await pw.chromium.launch(exe ? { executablePath: exe } : {});
  const targets = ["/pages/about.html", "/pages/faq.html", ...[...expected].map((f) => "/" + f.replace(/index\.html$/, ""))];
  for (const jsEnabled of [false, true]) {
    for (const path of targets) {
      const ctx = await browser.newContext({ viewport: { width: 360, height: 740 }, javaScriptEnabled: jsEnabled });
      const page = await ctx.newPage();
      const errs = [], csp = [], sizes = [];
      let reqs = 0;
      page.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
      page.on("pageerror", (e) => errs.push(String(e)));
      await page.route("**/*", (route) => (route.request().url().startsWith(base) ? route.continue() : route.abort()));
      page.on("response", async (r) => { if (r.url().startsWith(base)) { reqs++; try { sizes.push((await r.body()).length); } catch {} } });
      await page.addInitScript(() => document.addEventListener("securitypolicyviolation", (e) => console.error("CSPVIOLATION " + e.violatedDirective + " " + e.blockedURI)));
      await page.goto(base + path, { waitUntil: "load" });
      await page.waitForTimeout(500);
      const info = await page.evaluate(() => ({
        h1: (document.querySelector("h1") || {}).innerText || "",
        overflow: document.documentElement.scrollWidth > window.innerWidth + 1,
        bodyVisible: [...document.querySelectorAll("main p, main li")].every((e) => getComputedStyle(e).opacity !== "0")
      }));
      const cspErrs = errs.filter((e) => e.includes("CSPVIOLATION") || /Content Security Policy/i.test(e));
      const other = errs.filter((e) => !cspErrs.includes(e) && !/ERR_FAILED|net::|Failed to load resource/.test(e));
      const label = `${jsEnabled ? "JS on " : "JS off"} 360px ${path}`;
      check(info.h1.trim().length > 0, `${label}: H1 visible ("${info.h1.trim().slice(0, 40)}")`, `${label}: no visible H1`);
      check(!info.overflow, `${label}: no horizontal scroll`, `${label}: horizontal overflow`);
      check(info.bodyVisible, `${label}: text not hidden`, `${label}: some text has opacity 0`);
      check(cspErrs.length === 0, `${label}: no CSP violations`, `${label}: CSP violations ${cspErrs}`);
      check(other.length === 0, `${label}: no console errors`, `${label}: console errors ${other}`);
      if (jsEnabled) {
        const total = sizes.reduce((a, b) => a + b, 0);
        console.log(`       weight: ${reqs} same-origin requests, ${(total / 1024).toFixed(1)} KB uncompressed`);
      }
      await ctx.close();
    }
  }
  const css = readFileSync(join(ROOT, "css/articles.css"));
  console.log(`  articles.css: ${css.length} bytes (${gzipSync(css).length} bytes gzip)`);
  for (const f of ["articles/index.html", "pages/about.html", "pages/faq.html"]) {
    const b = readFileSync(join(ROOT, f));
    console.log(`  ${f}: ${b.length} bytes (${gzipSync(b).length} gzip)`);
  }
  await browser.close();
  server.close();
}
if (args.includes("--browser")) await browserChecks();

console.log(`\n${failures ? "FAILED" : "PASSED"}: ${failures} failure(s), ${warnings} warning(s)`);
process.exit(failures ? 1 : 0);
